[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package]
name = "kanoe"
version = "0.1.0"
authors = ["André Loureiro <loureiro.andrew@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.3"
